### ISSUE TITLE
OOM when training SQuAD 2.0 on 8 V100 GPUs (32G) for batch_size 8

### ISSUE THREAD

**Issue by yangapku** [zihangdai/xlnet#101]
Hi,

We are very eager to try XLNet on machine reading datasets. Luckily, we have 8 V100 GPUs, each with 32G memory. According to the readme, it can hold the setting of batch_size=8 with seq_len=512. However, when we ran the following command:

```
DATA_DIR=data/squad
INIT_CKPT_DIR=xlnet_cased_L-24_H-1024_A-16

python run_squad.py \
  --use_tpu=False \
  --num_hosts=1 \
  --num_core_per_host=8 \
  --use_bfloat16=False \
  --model_config_path=${INIT_CKPT_DIR}/xlnet_config.json \
  --spiece_model_file=${INIT_CKPT_DIR}/spiece.model \
  --output_dir=${DATA_DIR}/train_tf_record/ \
  --init_checkpoint=${INIT_CKPT_DIR}/xlnet_model.ckpt \
  --model_dir=output/ \
  --train_file=${DATA_DIR}/train-v2.0.json \
  --predict_file=${DATA_DIR}/dev-v2.0.json \
  --predict_dir=output/ \
  --uncased=False \
  --max_seq_length=512 \
  --do_train=True \
  --train_batch_size=8 \
  --do_predict=True \
  --predict_batch_size=8 \
  --learning_rate=3e-5 \
  --adam_epsilon=1e-6 \
  --iterations=1000 \
  --save_steps=1000 \
  --train_steps=48000 \
  --warmup_steps=6000 1>$PWD_DIR/log/train.log 2>&1
```
The program got OOM before the training began. Did we miss something to run it correctly? Or is the model just too large to run on these GPUs (unlike the readme says)?

**Comment by kimiyoung** [comment]
`train_batch_size` is the per-gpu batch size.

**Comment by tbright17** [comment]
I'm trying it on 4 P40 (22GB). Even with batch size 1 and max sequence length 128 OOM will occur. Do you have any progress on this problem?

**Comment by yangapku** [comment]
I see. Thank you for your help! But we encountered another issue #127 . Could you please have a look at it?
