### ISSUE TITLE
What's the factorization order in test time for downstream tasks?

### ISSUE THREAD

**Issue by shaform** [zihangdai/xlnet#103]
In test time for downstream tasks, which is true?

(1) Unlike pretraining, there are no masks in test time, i.e., each token can see all tokens from both directions.

(2) A fixed permutation is used, which is probably the order 1->2->3->...->n, i.e., the last token can see all tokens in the past, but the middle tokens cannot see the right-hand-side tokens.

(3) Other possibilities such as randomly sample many permutations.

**Comment by shaform** [comment]
It seems that it was mentioned here that during inference there is no permutation:
https://github.com/zihangdai/xlnet/issues/80#issuecomment-506839615

Since (1) would be unusually if it's not documented, I guess the correct answer to the original question is (2).

**Comment by lukemelas** [comment]
To confirm what @shaform said, it is (1): all tokens can see all tokens.
