### ISSUE TITLE
Comparison with GPT-2

### ISSUE THREAD

**Issue by rusiaaman** [zihangdai/xlnet#109]
In the paper results for RACE (Table-1) are provided for GPT which is a smaller model (~110M parameters) compared to BERT large and XLNet. I think it will be worthwhile to mention this in the caption, since GPT is a forgotten model after being replaced by GPT-2. 

Instead of GPT is it possible to have comparison with GPT-2, which is a newer model and more relevant?

**Comment by lukemelas** [comment]
I believe this should be just what you are looking for: https://medium.com/@amanrusia/xlnet-speaks-comparison-to-gpt-2-ea1a4e9ba39e

Just post if you have any more questions, otherwise you can close the issue.

**Comment by rusiaaman** [comment]
That article lacks a rigorous comparison in classification tasks, and it was meant to be a general indicative of performance (the question answering comparison was without beam search--only greedy decoding--and on limited examples).  But I think that measuring performance against GPT2 should not be a part of this work and I will close this issue.
