### ISSUE TITLE
error in pretrain an XLNet . train_gpu.py.

### ISSUE THREAD

**Issue by 3NFBAGDU** [zihangdai/xlnet#111]
I have successfully  ran  `spm_train \
	--input=$INPUT \
	--model_prefix=sp10m.cased.v3 \
	--vocab_size=32000 \
	--character_coverage=0.99995 \
	--model_type=unigram \
	--control_symbols=<cls>,<sep>,<pad>,<mask>,<eod> \
	--user_defined_symbols=<eop>,.,(,),",-,–,£,€ \
	--shuffle_input_sentence \
	--input_sentence_size=10000000`
and  `python data_utils.py \
	--bsz_per_host=32 \
	--num_core_per_host=16 \
	--seq_len=512 \
	--reuse_len=256 \
	--input_glob=*.txt \
	--save_dir=${SAVE_DIR} \
	--num_passes=20 \
	--bi_data=True \
	--sp_path=spiece.model \
	--mask_alpha=6 \
	--mask_beta=1 \
	--num_predict=85`.

now when i want to run train_gpu.py :
  `sudo python3 train_gpu.py --record_info_dir=/home/ubuntu/xlnet/training/tfrecords --train_batch_size=2048 --seq_len=512 --reuse_len=256 --mem_len=384 --perm_size=256 --n_layer=24 --d_model=1024 --d_embed=1024 --n_head=16 --d_head=64 --d_inner=4096 --untie_r=True --mask_alpha=6 --mask_beta=1 --num_predict=85 --model_dir=/home/ubuntu/axalimodeli` i have the error:

`/usr/local/lib/python3.5/dist-packages/tensorflow-plugins /home/ubuntu/.local/lib/python3.5/site-packages/tensorflow-plugins /usr/lib/python3/dist-packages/tensorflow-plugins /usr/lib/python3.5/dist-packages/tensorflow-plugins I0702 11:32:34.041983 139935611332352 train_gpu.py:319] n_token 32000 I0702 11:32:34.042275 139935611332352 data_utils.py:795] Use the following tfrecord dirs: ['/home/ubuntu/xlnet/training/tfrecords'] I0702 11:32:34.042413 139935611332352 data_utils.py:799] [0] Record glob: /home/ubuntu/xlnet/training/tfrecords/record_info-train-*.bsz-2048.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.json I0702 11:32:34.042960 139935611332352 data_utils.py:803] [0] Num of record info path: 0 I0702 11:32:34.043075 139935611332352 data_utils.py:836] [Dir 0] Number of chosen batches: 0 I0702 11:32:34.043182 139935611332352 data_utils.py:838] [Dir 0] Number of chosen files: 0 I0702 11:32:34.043281 139935611332352 data_utils.py:839] [] I0702 11:32:34.043379 139935611332352 data_utils.py:846] Total number of batches: 0 I0702 11:32:34.043897 139935611332352 data_utils.py:848] Total number of files: 0 I0702 11:32:34.044010 139935611332352 data_utils.py:849] [] I0702 11:32:34.044113 139935611332352 train_gpu.py:204] num of batches 0 I0702 11:32:34.044229 139935611332352 data_utils.py:555] Host 0 handles 0 files Traceback (most recent call last): File "train_gpu.py", line 328, in <module> tf.compat.v1.app.run() File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run _run_main(main, args) File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main sys.exit(main(argv)) File "train_gpu.py", line 324, in main train("/gpu:0") File "train_gpu.py", line 212, in train train_set = train_input_fn(params) File "/home/ubuntu/xlnet/data_utils.py", line 868, in input_fn num_predict=num_predict) File "/home/ubuntu/xlnet/data_utils.py", line 757, in get_dataset bsz_per_core=bsz_per_core) File "/home/ubuntu/xlnet/data_utils.py", line 566, in parse_files_to_dataset dataset = tf.data.TFRecordDataset(dataset) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 335, in __init__ filenames, compression_type, buffer_size, num_parallel_reads) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 295, in __init__ filenames = _create_or_validate_filenames_dataset(filenames) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/readers.py", line 50, in _create_or_validate_filenames_dataset "filenamesmust be atf.data.Datasetoftf.stringelements.") TypeError:filenamesmust be atf.data.Datasetoftf.string elements.`

Can you help me to solve this case.  data_utils.py make the tfrecords file in this directory '/home/ubuntu/xlnet/training/tfrecords'.

**Comment by graykode** [comment]
This is because your file didnt not match `xlnet/proc_data/example/tfrecords/*.json` and `train_gpu` option. you should be same option `data_util.py` and `train_gpu`

**Comment by 3NFBAGDU** [comment]
`sudo python3 data_utils.py --bsz_per_host=32 --num_core_per_host=16 --seq_len=512 --reuse_len=256 --input_glob=books-sentences.txt --save_dir=lado.txt --num_passes=20 --bi_data=True --sp_path=/home/ubuntu/giorgi/sp10m.cased.v3.model --mask_alpha=6 --mask_beta=1 --num_predict=85 `

`sudo python3 train_gpu.py --record_info_dir=/home/ubuntu/xlnet/training/tfrecords --train_batch_size=2048 --seq_len=512 --reuse_len=256 --mem_len=384 --perm_size=256     --n_layer=24 --d_model=1024 --d_embed=1024 --n_head=16 --d_head=64 --d_inner=4096 --untie_r=True --mask_alpha=6 --mask_beta=1 --num_predict=85`

--seq_len, --reuse_len  is same in both.
What parameter Should i change in data_utils.py?

**Comment by SuMarsss** [comment]
> meter Should i change in data_utils.py?

The parameter `train_batch_size`should be 32 ,which is equal to `bsz_per_host`

**Comment by 3NFBAGDU** [comment]
> > meter Should i change in data_utils.py?
> 
> The parameter `train_batch_size`should be 32 ,which is equal to `bsz_per_host`

i have changed train_batch_size = 32, but got same error `TypeError: Expected binary or unicode string, got None`

**Comment by volker42maru** [comment]
Had the same issue. You have to set the `uncased` flag in either `data_utils.py` (preproc) or `train.py`, because they are set to different default values within these files.

**Comment by 3NFBAGDU** [comment]
> Had the same issue. You have to set the `uncased` flag in either `data_utils.py` (preproc) or `train.py`, because they are set to different default values within these files.

`sudo python3 train_gpu.py --record_info_dir=fix3/tfrecords --train_batch_size=32 --seq_len=512 --reuse_len=256 --mem_len=384 --perm_size=256 --n_layer=24 --d_model=1024 --d_embed=1024 --n_head=16 --d_head=64 --d_inner=4096 --untie_r=True --model_dir='my_model' --uncased=False `

`sudo python3 data_utils.py --bsz_per_host=32 --num_core_per_host=16 --seq_len=512 --reuse_len=256 --input_glob=books-sentences.txt --save_dir=fix3 --num_passes=20 --bi_data=True --sp_path=/home/ubuntu/giorgi/sp10m.cased.v3.model --mask_alpha=6 --mask_beta=1 --num_predict=85 --uncased=False`

same error : `TypeError: `filenames` must be a `tf.data.Dataset` of `tf.string` elements`.

**Comment by 3NFBAGDU** [comment]
> Had the same issue. You have to set the `uncased` flag in either `data_utils.py` (preproc) or `train.py`, because they are set to different default values within these files.

`/usr/lib/python3/dist-packages/tensorflow-plugins                                                                       /usr/lib/python3.5/dist-packages/tensorflow-plugins                                                                     /usr/local/lib/python3.5/dist-packages/tensorflow-plugins                                                               /home/ubuntu/.local/lib/python3.5/site-packages/tensorflow-plugins                                                      WARNING: Logging before flag parsing goes to stderr.                                                                    W0708 08:40:08.607083 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/model_utils.py:295: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.                                                                                                                                                               I0708 08:40:08.610028 139941971003136 train_gpu.py:327] n_token 32000                                                   I0708 08:40:08.610235 139941971003136 data_utils.py:797] Use the following tfrecord dirs: ['fix3/tfrecords']            I0708 08:40:08.610371 139941971003136 data_utils.py:801] [0] Record glob: fix3/tfrecords/record_info-train-0-0.bsz-32.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.json                                                                        I0708 08:40:08.611006 139941971003136 data_utils.py:805] [0] Num of record info path: 1                                 W0708 08:40:08.611171 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/data_utils.py:818: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.                                                                                                                                                                                I0708 08:40:08.611785 139941971003136 data_utils.py:838] [Dir 0] Number of chosen batches: 6672                         I0708 08:40:08.611899 139941971003136 data_utils.py:840] [Dir 0] Number of chosen files: 1                              I0708 08:40:08.611995 139941971003136 data_utils.py:841] ['fix3/tfrecords/train-0-0.bsz-32.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.tfrecords']                                                                                            I0708 08:40:08.612092 139941971003136 data_utils.py:848] Total number of batches: 6672                                  I0708 08:40:08.612574 139941971003136 data_utils.py:850] Total number of files: 1                                       I0708 08:40:08.612675 139941971003136 data_utils.py:851] ['fix3/tfrecords/train-0-0.bsz-32.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.tfrecords']                                                                                            I0708 08:40:08.612774 139941971003136 train_gpu.py:211] num of batches 6672                                             I0708 08:40:08.612880 139941971003136 data_utils.py:555] Host 0 handles 1 files                                         W0708 08:40:08.648264 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/data_utils.py:661: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.                                                                                                                                                                       W0708 08:40:08.648567 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/data_utils.py:669: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.                                                                                                                                                             W0708 08:40:08.667379 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/data_utils.py:597: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.                                                                                                                                                                            W0708 08:40:08.677403 139941971003136 deprecation.py:323] From /home/ubuntu/xlnet/data_utils.py:614: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.        Instructions for updating:                                                                                              Use tf.where in 2.0, which has the same broadcast rule as np.where                                                      W0708 08:40:08.831998 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/data_utils.py:744: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.                                                                                                                                                                      I0708 08:40:08.832251 139941971003136 data_utils.py:744] target_mask: Tensor("Reshape_6:0", shape=(85,), dtype=float32) I0708 08:40:08.832447 139941971003136 data_utils.py:744] label: Tensor("Cast_6:0", shape=(1,), dtype=int32)             I0708 08:40:08.832623 139941971003136 data_utils.py:744] perm_mask: Tensor("Reshape_7:0", shape=(512, 512), dtype=float32)                                                                                                                      I0708 08:40:08.832789 139941971003136 data_utils.py:744] target: Tensor("Cast_7:0", shape=(85,), dtype=int32)           I0708 08:40:08.832949 139941971003136 data_utils.py:744] input_q: Tensor("Reshape_9:0", shape=(512,), dtype=float32)    I0708 08:40:08.833099 139941971003136 data_utils.py:744] seg_id: Tensor("Cast_8:0", shape=(512,), dtype=int32)          I0708 08:40:08.833247 139941971003136 data_utils.py:744] target_mapping: Tensor("Reshape_4:0", shape=(85, 512), dtype=float32)                                                                                                                  I0708 08:40:08.833401 139941971003136 data_utils.py:744] input_k: Tensor("Cast_9:0", shape=(512,), dtype=int32)         W0708 08:40:08.867602 139941971003136 deprecation.py:323] From train_gpu.py:221: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.                          Instructions for updating:                                                                                              Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.                 W0708 08:40:08.974613 139941971003136 deprecation_wrapper.py:119] From train_gpu.py:238: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.                                                                                                                                                                                      W0708 08:40:08.974895 139941971003136 deprecation_wrapper.py:119] From train_gpu.py:238: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.                                                                                                                                                                              W0708 08:40:08.999852 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/xlnet.py:75: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.                                                                                                                                                                                   my_model                                                                                                                I0708 08:40:09.001743 139941971003136 modeling.py:453] memory input [<tf.Tensor 'Placeholder:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_1:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_2:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_3:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_4:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_5:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_6:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_7:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_8:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_9:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_10:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_11:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_12:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_13:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_14:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_15:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_16:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_17:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_18:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_19:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_20:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_21:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_22:0' shape=(384, 4, 1024) dtype=float32>, <tf.Tensor 'Placeholder_23:0' shape=(384, 4, 1024) dtype=float32>]                I0708 08:40:09.001895 139941971003136 modeling.py:455] Use float type <dtype: 'float32'>                                W0708 08:40:09.071126 139941971003136 deprecation.py:506] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.                                                                                  Instructions for updating:                                                                                              Call initializer instance with the dtype argument instead of passing it to the constructor                              W0708 08:40:09.085693 139941971003136 deprecation.py:323] From /home/ubuntu/xlnet/modeling.py:535: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.                                          Instructions for updating:                                                                                              Use keras.layers.dropout instead.                                                                                       W0708 08:40:09.211584 139941971003136 deprecation_wrapper.py:119] From /home/ubuntu/xlnet/modeling.py:236: The name tf.debugging.assert_equal is deprecated. Please use tf.compat.v1.debugging.assert_equal instead.                                                                                                                                                    E0708 08:40:09.222637 139941971003136 tf_should_use.py:71] ==================================                           Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                       <tf.Operation 'model/transformer/assert_equal/Assert/Assert' type=Assert>                                               If you want to mark it as used call its "mark_used()" method.                                                           It was originally created here:                                                                                           File "train_gpu.py", line 336, in <module>                                                                                tf.compat.v1.app.run()  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run                                                                                                                        _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run                                                                                               _run_main(main, args)  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main                sys.exit(main(argv))  File "train_gpu.py", line 331, in main                                                            train("/gpu:0")  File "train_gpu.py", line 248, in train                                                                mems=mems_i)  File "train_gpu.py", line 167, in single_core_graph                                                       is_training=is_training)  File "train_gpu.py", line 143, in model_fn                                                    FLAGS, features, labels, mems, is_training)  File "/home/ubuntu/xlnet/function_builder.py", line 130, in get_loss       return two_stream_loss(FLAGS, features, labels, mems, is_training)  File "/home/ubuntu/xlnet/function_builder.py", line 90, in two_stream_loss                                                                                                  inp_q=inp_q)  File "/home/ubuntu/xlnet/xlnet.py", line 222, in __init__                                                 ) = modeling.transformer_xl(**tfm_args)  File "/home/ubuntu/xlnet/modeling.py", line 567, in transformer_xl             bsz=bsz, dtype=tf_float)  File "/home/ubuntu/xlnet/modeling.py", line 236, in relative_positional_encoding              tf.debugging.assert_equal(bsz % 2, 0)  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/check_ops.py", line 557, in assert_equal                                                                                              return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py", line 193, in wrapped                                                               return _add_should_use_warning(fn(*args, **kwargs))                                                                 ==================================                                                                                      W0708 08:40:10.172199 139941971003136 lazy_loader.py:50]                                                                The TensorFlow contrib module will not be included in TensorFlow 2.0.                                                   For more information, please see:                                                                                         * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md                                   * https://github.com/tensorflow/addons                                                                                  * https://github.com/tensorflow/io (for I/O related ops)                                                              If you depend on functionality not listed there, please file an issue.                                                                                                                                                                          W0708 08:40:10.364219 139941971003136 deprecation.py:323] From /home/ubuntu/xlnet/modeling.py:67: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.                                             Instructions for updating:                                                                                              Use keras.layers.dense instead. `

Is this norm?

**Comment by volker42maru** [comment]
Check if the name of your generated `.json` file includes the same param values as you use in `train.py`. In your case prolly: `record_info-train-0-0.bsz-32.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.json`

**Comment by rkcalnode** [comment]
I have the same problem. And try below, this error was solved.
> Had the same issue. You have to set the uncased flag in either data_utils.py (preproc) or train.py, > because they are set to different default values within these files.

But Another assertion error occured in modeling.py(line: 236)
` assert bsz%2 == 0 `

Result of print bsz is below. Tensor was passed. But is it expected?

Inserted code in modeling.py (line 233)
```
    print('***** bsz ***** : {}'.format(bsz))
    print('***** type of bsz ***** : {}'.format(type(bsz)))
    print('***** bsz%2 ***** : {}'.format(bsz%2))
...
    if bsz is not None:
```

Stdout
```
***** bsz ***** : Tensor("model/transformer/strided_slice:0", shape=(), dtype=int32, device=/gpu:0)
***** type of bsz ***** : <class 'tensorflow.python.framework.ops.Tensor'>
***** bsz%2 ***** : Tensor("model/transformer/mod:0", shape=(), dtype=int32, device=/gpu:0)
```

**Comment by hockeybro12** [comment]
@rkcalnode  That assertion is buggy, so if your batch size is divisible by 2 then just comment it out.
