### ISSUE TITLE
where should I put the result of prepro_squad.sh?

### ISSUE THREAD

**Issue by MaXXXXfeng** [zihangdai/xlnet#118]
I am trying to run Squad 2.0 task on a single GPU, which refer to #64 。 
I am not sure where to put the result of prepro_squad.sh, since I get a error message 
`ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0 '`
Maybe I put the result file on wrong path or there are something wrong with the tfrecord file. 
Are there any config ot path I need to modify before I run prepro_squad.sh or run_squad.sh ?

**Comment by leelaylay** [comment]
It may have something to do with the file format of the tf record. 
See: https://github.com/tensorflow/models/issues/4483
