### ISSUE TITLE
Pretraining uncased flag

### ISSUE THREAD

**Issue by Colanim** [zihangdai/xlnet#123]
In the [Pretraining section of the README](https://github.com/zihangdai/xlnet#pretraining-with-xlnet), when giving example of flags for `data_utils.py` script, the flag `uncased` is not specified, and the default value is `True`.

Therefore, the model trained with the given command will be uncased.

**For training [XLNet-Large-Cased](https://storage.googleapis.com/xlnet/released_models/cased_L-24_H-1024_A-16.zip), you set the flag `uncased` to `False`, am I right ?**

If so, can you provide the exact flags used to train [XLNet-Large-Cased](https://storage.googleapis.com/xlnet/released_models/cased_L-24_H-1024_A-16.zip) ?

**Comment by bzantium** [comment]
You are right. You should specify --uncased=False when you run data_utils.py

**Comment by antonyscerri** [comment]
Could you please update the readme to reflect this, as i just went through the same process and having spent a long time creating TF records to fine tune the pre-training I cannot use them.

**Comment by bzantium** [comment]
I think it is better to change the default value to False as: https://github.com/zihangdai/xlnet/pull/121/commits/1ea884d155cf789829fa7e0fa384b6987de4b809

**Comment by antonyscerri** [comment]
That works, sorry hadnt seen a commit attached to the issue.
