### ISSUE TITLE
assert bsz % 2 == 0 AssertionError

### ISSUE THREAD

**Issue by knightBoy** [zihangdai/xlnet#132]
I process my data and train the model as the following scripts, but I always get AssertionError:

1. preprocess the data

`python3 data_utils.py --bsz_per_host=16 --num_core_per_host=8 --seq_len=512 --reuse_len=256 --input_glob=/data/xlnet/pretrain/total_test.txt --save_dir=/data/xlnet/pretrain/proc_data --num_passes=20 --bi_data=True --sp_path=/data/xlnet/pretrain/spiece.model --mask_alpha=6 --mask_beta=1 --num_predict=16`

2. train the model

`python3 train_gpu.py --num_core_per_host=8 --record_info_dir=/data/xlnet/pretrain/proc_data/wiki/tfrecords --train_batch_size=16 --model_dir=/data/xlnet/pretrain/model --seq_len=512 --reuse_len=256 --mem_len=64 --perm_size=256 --n_layer=24 --d_model=1024 --d_embed=1024 --n_head=16 --d_head=64 --d_inner=4096 --untie_r=True --mask_alpha=6 --mask_beta=1 --num_predict=16 --uncased=True`

I think the train_batch_size(16) must can be divisible by 2. Is there someting wrong?

Besides: I used a pretrained Chinese sentencepiece model whose vocab size is 100000, so I change the VOCAB_SIZE in `data_util.py`. Is this OK?

**Comment by bzantium** [comment]
I had the same error. I realized that bsz is tensor type so the assertion should be for tensor type.
please refer to:
https://github.com/zihangdai/xlnet/pull/121/commits/7ef2f2ddb6aea4ab931b2f5762579e419c78944c

**Comment by knightBoy** [comment]
yeah, you are right. I have also found this bug.
