### ISSUE TITLE
New Feature Request  Large Batch Optimization

### ISSUE THREAD

**Issue by ricklentz** [zihangdai/xlnet#138]
Feature request: Implement the large batch optimization technique (LAMB) outlined in "Large Batch Optimization for Deep Learning: Training BERT in 76 minutes"
[ref] https://arxiv.org/abs/1904.00962

**Comment by ymcui** [comment]
I have one :)
https://github.com/ymcui/LAMB_Optimizer_TF

**Comment by ricklentz** [comment]
Awesome! Thank you.
