### ISSUE TITLE
The model did not distinguish all possible factorization order

### ISSUE THREAD

**Issue by world2vec** [zihangdai/xlnet#14]
Good paper!
I am confused about the factorization order. Looks the model did not distinguish all possible factorization order. Follow Figure1 to predict x3, the model can not distinguish permutation Pa(2-4-3) with Pb(4-2-3) like traditional AR model, so the model did not model all possible factorization order?

**Comment by kimiyoung** [comment]
When you predict x3, 2-4-3 and 4-2-3 are the same. But when you predict x2 or x4, these two are different. Here we use x3 just as an example; in practice, other positions should be considered, too.

**Comment by amxineohp** [comment]
For a tradition AR(L2R), when predict x2, x4, they are different and when predict x3 they are also different.
So I still think L2R can model all possible permutation and xlnet can not.

**Comment by kimiyoung** [comment]
Permuting the sequence order is different from permuting the factorization order (See Remark in Sec 2.2). We don't permute the sequence order as in NADE because that would essentially make the model orderless, which is reduced to low-capacity bag-of-words (See related work in Sec 1).

**Comment by amxineohp** [comment]
For sequence without position embedding like S1(x1, x2), S2(x2, x1), if the model model all permuting, it will reduced to low-capacity bag-of-words because the 2 seqs have the same set of permuting. But with position embedding the 2 seqs have different set of all permuting, so the model will not reduced to bag-of-words.  For S1  the permuting is [L1(x1), L2(x2)], [L2(x2), L1(x1)] for S2 it is [L1(x2), L2(x1)], [L2(x1), L1(x2], L1, L2 is the location, they have different set of permuting.

**Comment by kimiyoung** [comment]
[L1(x1), L2(x2)] and [L2(x2), L1(x1)] are the same for a Transformer(-XL), because the position is the only thing that defines the sequence order.

**Comment by amxineohp** [comment]
I am still confused. Refer formula 3 in the paper  pθ(x_zt) | x_z<t) ), here x_z<t ignore the permuting order (the transormer-xl can not distinguish the permuting order)? For a seq x = (x1,x2,x3), for a specific permuting (x2, x3, x1), to calculate p(x) = p(x2|order())*p(x3|order(x2))*p(x1|order(x2,x3)). if x_z<t ignore the permuting order, p(x1|ignore_permuting_order(x2, x3)) = p(x1|order(x2, x3)) + p(x1|order(x3, x2)), this way  it looks formula 3 not calculate p(x), sorry for my poor math knowledge, I can not understand why this way still model the objective: XLNet maximizes the expected log likelihood of a sequence w.r.t. all possible permutations of the factorization order.
