### ISSUE TITLE
ImportError: No module named 'tensorflow.contrib.tpu.proto'

### ISSUE THREAD

**Issue by dhlee347** [zihangdai/xlnet#154]
I tried to run 'train.py' for pretraining xlnet. I use deep learning vm with tensorflow 1.14.0 in GCP. What happened? I cannot find the module in tensorflow.

**Comment by rusiaaman** [comment]
While we wait for the authors to specify the exact version of tensorflow they have used to pre-train, why don't you try tensorflow==1.13.1. The import error is gone, but I haven't tested it on real TPUs.

**Comment by dhlee347** [comment]
Thanks very much ! It works well :)
