### ISSUE TITLE
Are the code of sentencepiece model training "spm_train" released?

### ISSUE THREAD

**Issue by JMistral** [zihangdai/xlnet#162]
Couldn't find "spm_train" to train sentence piece model

**Comment by stefan-it** [comment]
I think you can find the `spm_train` parameters in the readme (pretraining section):

https://github.com/zihangdai/xlnet#pretraining-with-xlnet

**Comment by JMistral** [comment]
> I think you can find the `spm_train` parameters in the readme (pretraining section):
> 
> https://github.com/zihangdai/xlnet#pretraining-with-xlnet

Thanks for replying, I saw the parameters but was looking for the code to train the spm model

**Comment by JMistral** [comment]
Found the solution in SentencePiece git repo, closing the issue
