### ISSUE TITLE
TypeError for pretraining on new dataset. `filenames` must be a `tf.data.Dataset` of `tf.string` elements.

### ISSUE THREAD

**Issue by vanh17** [zihangdai/xlnet#166]
python train_gpu.py \
>   --corpus_info_path=/net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/corpus_info.json \
>   --model_dir=/net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/models/base_cased \
>   --record_info_dir=/net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/tfrecords \
>  --train_batch_size=8 \
>   --seq_len=512 \
>   --reuse_len=256 \
>   --mem_len=384 \
>   --perm_size=256 \
>   --n_layer=12 \
>   --d_model=768 \
>   --d_embed=768 \
>   --n_head=12 \
>   --d_head=64 \
>   --d_inner=4096 \
>   --untie_r=True \
>   --mask_alpha=6 \
>   --mask_beta=1 \
>   --num_predict=85 \
>   --train_steps=1000000 \
>   --iterations=10000\

I got this error immediately:

I0716 16:32:30.858338 140514418988864 train_gpu.py:319] n_token 32000
I0716 16:32:30.859011 140514418988864 data_utils.py:795] Use the following tfrecord dirs: ['/net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/tfrecords']
I0716 16:32:30.860071 140514418988864 data_utils.py:799] [0] Record glob: /net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/tfrecords/record_info-train-*.bsz-8.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.json
I0716 16:32:30.860581 140514418988864 data_utils.py:803] [0] Num of record info path: 0
I0716 16:32:30.860665 140514418988864 data_utils.py:836] [Dir 0] Number of chosen batches: 0
I0716 16:32:30.860707 140514418988864 data_utils.py:838] [Dir 0] Number of chosen files: 0
I0716 16:32:30.860743 140514418988864 data_utils.py:839] []
I0716 16:32:30.860780 140514418988864 data_utils.py:846] Total number of batches: 0
I0716 16:32:30.860979 140514418988864 data_utils.py:848] Total number of files: 0
I0716 16:32:30.861017 140514418988864 data_utils.py:849] []
I0716 16:32:30.861056 140514418988864 train_gpu.py:204] num of batches 0
I0716 16:32:30.861101 140514418988864 data_utils.py:555] Host 0 handles 0 files
Traceback (most recent call last):
  File "train_gpu.py", line 328, in <module>
    tf.app.run()
  File "/net/vaosl01/opt/NFS/mimic_hv4/anaconda3/envs/henry/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_gpu.py", line 324, in main
    train("/gpu:0")
  File "train_gpu.py", line 212, in train
    train_set = train_input_fn(params)
  File "/net/vaosl01/opt/NFS/hv4/xlnet-pretrain-mimic/xlnet/data_utils.py", line 868, in input_fn
    num_predict=num_predict)
  File "/net/vaosl01/opt/NFS/hv4/xlnet-pretrain-mimic/xlnet/data_utils.py", line 757, in get_dataset
    bsz_per_core=bsz_per_core)
  File "/net/vaosl01/opt/NFS/hv4/xlnet-pretrain-mimic/xlnet/data_utils.py", line 566, in parse_files_to_dataset
    dataset = tf.data.TFRecordDataset(dataset)
  File "/net/vaosl01/opt/NFS/mimic_hv4/anaconda3/envs/henry/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 247, in __init__
    filenames, compression_type, buffer_size, num_parallel_reads)
  File "/net/vaosl01/opt/NFS/mimic_hv4/anaconda3/envs/henry/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 193, in __init__
    "`filenames` must be a `tf.data.Dataset` of `tf.string` elements.")
TypeError: `filenames` must be a `tf.data.Dataset` of `tf.string` elements.

**Comment by rusiaaman** [comment]
> /net/vaosl01/opt/NFS/mimic_hv4/data/xlnetMimic/tfrecords/record_info-train-*.bsz-8.seqlen-512.reuse-256.bi.alpha-6.beta-1.fnp-85.json

Please check if there exists a file matching the above glob. This error is obtained mostly when there is a mismatch of parameters between data pre-processing through `data_utils.py` and the parameters passed in to training. Check bsz_per_host, seq_len, reuse_len, use_bidata, alpha and beta used for pre-processing.

**Comment by vanh17** [comment]
Thank you. The issue is because of the mismatch in default value of ``uncased`` between data_utils.py and train_gpu.py

**Comment by sandeepKBM** [comment]
I am having the same issue , can I get some help. Same error and everything done all the changes instructed but still it doesn't work
