### ISSUE TITLE
Pooled output is size [max_len, hidden_size]. Shouldn't it be [batch_size, hidden_size]?

### ISSUE THREAD

**Issue by kmeng01** [zihangdai/xlnet#175]
I'm trying to fine-tune XLNet-Base to a custom text classification task using the provided abstraction in `xlnet.py`. I pass into the model tensors `input_ids`, `mask_ids`, and `segment_ids`, all of size `(None, max_len)`. `max_len` is `200`, and `None` represents the variable batch size.

After fprop, the pooled output is of shape `(max_len, hidden_size)`, which in my XLNet-Base version, is `(200, 768)`. Shouldn't this be `(None, 768)`? i.e. a pooled output of size 768 for each of the samples in the batch.

Help is greatly appreciated!

**Comment by huseinzol05** [comment]
Your input should transpose, instead, `[None, max_len]`, become `[max_len, None]`.
