### ISSUE TITLE
How to use XLnet as language model?

### ISSUE THREAD

**Issue by Shujian2015** [zihangdai/xlnet#18]
Thanks for the great paper and Git repo. My question is how to use XLnet as language model?

**Comment by kimiyoung** [comment]
To use XLNet as a language model, simply change the attention masks to be unidirectional. This can be achieved by passing a `perm_mask` to the [`transformer_xl`](https://github.com/zihangdai/xlnet/blob/master/modeling.py#L383) function. Moreover, if you are interested in building a Transformer-XL-like LM with memory, pass `mems` to the function, too.

**Comment by Shujian2015** [comment]
Thanks, Zhilin!

**Comment by lanwuwei** [comment]
Hi Zhilin,
Have you tried XLNet for LM Benchmark? Does it show better performance compared to Transformer-XL?
