### ISSUE TITLE
The poor performance when trying to evaluate on CoLA Dataset

### ISSUE THREAD

**Issue by UsedToBe97** [zihangdai/xlnet#21]
I tried to use XLNet-large-cased ckpt to evaluate on the CoLA dataset. However, it turned out that the accuracy on eval.tsv is only 0.042... 

I modified run_classifier.py like following.
```python
class ColaProcessor(GLUEProcessor):
  def __init__(self):
    super(ColaProcessor, self).__init__()
    self.label_column = 1
    self.text_a_column = 3
    self.test_text_a_column = 1

  def get_labels(self):
    return ["0", "1"]

  def _create_examples(self, lines, set_type):
    """Creates examples for the training and dev sets."""
    examples = []
    for (i, line) in enumerate(lines):
      if i == 0 and self.contains_header and set_type != "test":
        continue
      if i == 0 and self.test_contains_header and set_type == "test":
        continue
      guid = "%s-%s" % (set_type, i)

      a_column = (self.text_a_column if set_type != "test" else
          self.test_text_a_column)

      # there are some incomplete lines in QNLI
      if len(line) <= a_column:
        tf.logging.warning('Incomplete line, ignored.')
        continue
      text_a = line[a_column]

      if set_type == "test":
        label = self.get_labels()[0]
      else:
        if len(line) <= self.label_column:
          tf.logging.warning('Incomplete line, ignored.')
          continue
        label = line[self.label_column]
      examples.append(
          InputExample(guid=guid, text_a=text_a, text_b=None, label=label))
    return examples
```
The command line is the following:
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 python run_classifier.py \
  --do_train=True \
  --do_eval=True \
  --do_predict=True \
  --eval_split=eval \
  --task_name=CoLA \
  --data_dir=${GLUE_DIR}/CoLA \
  --output_dir=proc_data/${TASK_NAME} \
  --model_dir=exp/${TASK_NAME} \
  --predict_dir=result/${TASK_NAME} \
  --uncased=False \
  --spiece_model_file=${LARGE_DIR}/spiece.model \
  --model_config_path=${LARGE_DIR}/xlnet_config.json \
  --init_checkpoint=${LARGE_DIR}/xlnet_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=8 \
  --num_hosts=1 \
  --num_core_per_host=4 \
  --learning_rate=5e-5 \
  --train_steps=1200 \
  --warmup_steps=120 \
  --save_steps=600 \
  --is_regression=False
```

Could anyone help me with this?

**Comment by zihangdai** [comment]
For CoLA, we used `train_batch_size` 128 and trained for 3000 steps with 500 `warmup_steps`.

**Comment by UsedToBe97** [comment]
@zihangdai 
Thanks, Zihang !
I'll try this setting later : )

**Comment by randomtutu** [comment]
> @zihangdai
> Thanks, Zihang !
> I'll try this setting later : )

Hi
Have u tried the task again these days ?
i got some poor results in sts-b, which using only 1 GPU with 16G memory while training.(batch size=8, seq_len=128)  
i guess the poor performance of the model might due to the small batch size.
i wanna know ur model performance which using 4 GPU while training.
thx

**Comment by UsedToBe97** [comment]
> > @zihangdai
> > Thanks, Zihang !
> > I'll try this setting later : )
> 
> Hi
> Have u tried the task again these days ?
> i got some poor results in sts-b, which using only 1 GPU with 16G memory while training.(batch size=8, seq_len=128)
> i guess the poor performance of the model might due to the small batch size.
> i wanna know ur model performance which using 4 GPU while training.
> thx

The sts-b parameter works fine. I used 4 Titan-X GPU to train and got 90.4/90.0 result.
The `batch_size` is essential for you to reproduce the result, and I think `batch_size=8` means 8 for each GPU. Maybe you can do gradient accumulation : )

**Comment by aisheh90** [comment]
@UsedToBe97 

Hi
Did you try to predict using cola processor?
I am using the same cola class processor you write, it works fine for training and validation, but doesn't for test prediction?

I am using the following command to predict:
  --do_train=False\
  --do_eval=False \
  --eval_split=test\
  --do_predict=True \
  --task_name=cola 

But I got the following error:
TypeError: Expected binary or unicode string, got None
