### ISSUE TITLE
A Question about "How Standard LM Parameterization Fails"

### ISSUE THREAD

**Issue by FisheWYZ** [zihangdai/xlnet#23]
![image](https://user-images.githubusercontent.com/37647151/59960820-fdaca700-9500-11e9-8aaf-6116313cbf82.png)

I just use the screenshot from the appendix of the paper for simplicity.

My question is, based on the first condition, it seems that the second equation does not hold.
For two reasons (Assume we're predicting 3rd element with z_{<3} from permutation {x2, x1, x3, x4} and {x2, x1, x4, x3}, namely x3 and x4 respectively):
1) Since i =3<>j=4, even though the input to h(z_{<3}) are the same {e(x2), e(x1)}, the weights are different, {w_23, w_13} to predict x3, and {w_24. w_14} to predict x4.
   For all layers, the weights are also different for different target predictions, even with same input neurons.
   Therefore, h(x_{z<t}) does not equal for the two permutations, even with the same prefix.

2)  Since i <> j, if:
  2.1.  X_i <> X_j, then e(X_i) <> e(X_j), the first term in exp(*) does not equal when predicting z_3
         (i.e. x3 and x4 are the same word)
  2.2.  X_i = X_j, then e(X_i) = e(X_j),  the first term in exp(*) equals when predicting z_3

So the e(x) h(x_{z<t}) may not hold for the two permutations with same prefix.

This is my confusion. Please correct me if I'm wrong. 

Thx a lot.

**Comment by kimiyoung** [comment]
It seems to me that you are confusing a "variable" with a "value". Upper case means variables and lower case means values. The second equation says, when X_3 and X_4 take the same value x, they are given the same distributions by the model.

**Comment by FisheWYZ** [comment]
Thank you
