### ISSUE TITLE
Can I run sentence relevance appliance with only one 1080Ti GPU?

### ISSUE THREAD

**Issue by manhongxiang** [zihangdai/xlnet#244]
When I try to run, it keeps running into ResourceExhaustedError [OOM], even when I set train_batch_size=1 and max_seq_length=50. Its performance may be poor, but I just want to see it running successfully first, but still OOM.
    I'm a newbie. Could you give some advice or instruction?

**Comment by hqsiswiliam** [comment]
I think you can reduce the number of batch size, and make sure `num_core_per_host=1`

**Comment by manhongxiang** [comment]
> I think you can reduce the number of batch size, and make sure `num_core_per_host=1`

Thank you for your reply. I finally found the reason. It's weird but I just used the wrong python and tensorflow version. The problem disappeared when I use py27 and tf1.13.1
