### ISSUE TITLE
Throws an exception while trying to use with Colab TPU[with solution]

### ISSUE THREAD

**Issue by aditya-malte** [zihangdai/xlnet#31]
Hello,
The run_classifier.py gives out an int error when performing eval on the pretrained model after finetuning:
invalid literal for int() with base 10: 'gs://my_bert_2/xlnet/models/TASK/xlnet_model.ckpt'.

Solution:
Adding a try-catch block at line 776 of run_classifier:

        try:
            global_step = int(cur_filename.split("-")[-1])
            tf.logging.info("Add {} to eval list.".format(cur_filename))
            steps_and_files.append([global_step, cur_filename])
        except Exception:
            print(cur_filename+" skipped")

Best,
Aditya Malte

**Comment by zihangdai** [comment]
Hi Aditya, thank you for letting us know the problem and a solution. We haven't tested the model on colab yet. But from the error you got, it looks like it's trying to evaluate the non-finetuned ckpt `xlnet_model.ckpt` directly. Is that correctly?

**Comment by aditya-malte** [comment]
Hello
The problem is that the pretrained model provided is by the name xlnet_model.ckpt, hence it remains even after finetuning.
However during evaluation, when all filename strings are split on hyphen, and the last element chosen as global_step, then this error occurs.

**Comment by CharlieBickerton** [comment]
@aditya-malte Do you have a working TPU colab notebook? Please share if so

**Comment by aditya-malte** [comment]
It is almost complete for the single and double sentence task, will be sharing soon.

**Comment by kimiyoung** [comment]
@aditya-malte It seems to me that you set `model_dir` as the one that holds pretrained models, which is not our intended usage. We expect `model_dir` to be a separate folder. Could you confirm that this is the case? And I will update README to highlight this.

**Comment by aditya-malte** [comment]
Yes, I have updated my repo accordingly,
Now, MODEL_DIR is a separate folder that will hold the pretrained weights files and output dir the one which will hold the output weights
