### ISSUE TITLE
Could you check the memory usage for XL-large model?

### ISSUE THREAD

**Issue by ZizhenWang** [zihangdai/xlnet#42]
I use a single V100 GPU with 32G RAM, and run the `train sts-b` script given in `readme`. The script runs succeed when I set **batch size=4**, or it will stop with OOM error. This phenomenon is different from the description in the memory usage table. So could you check the number in that table?

p.s. I notice you set **batch size = 8** even you use **4 GPU**.

**Comment by kimiyoung** [comment]
A 32G memory GPU should be able to support a batch size of 8-16 with a `max_seq_length` of 128. You might want to double check the other hyperparameters and the TF version (tested under 1.13.1).

`train_batch_size` is per-GPU batch size (see Notes in https://github.com/zihangdai/xlnet#1-sts-b-sentence-pair-relevance-regression-with-gpus), so we are effectively using a batch size of 32 with 4 GPUs.

**Comment by ZizhenWang** [comment]
Ok, thanks to your reply.
