### ISSUE TITLE
Imdb classification taks - colab notebook (GPU)

### ISSUE THREAD

**Issue by CharlieBickerton** [zihangdai/xlnet#44]
I have just successfully trained the imdb classification task on a colab notebook:

If this is of interest to annoying the notebook code is here: https://github.com/CharlieBickerton/xlnet/blob/master/XLNet_imdb_GPU.ipynb

I've only just finished so it's not as clean as it could be.

**Comment by CharlieBickerton** [comment]
@kimiyoung @zihangdai if I clean this up would it be worth a PR? So that colab users without a GCP account can expertiment with XLNet?

**Comment by zihangdai** [comment]
@CharlieBickerton, does this only include GPU usage or also TPU?

**Comment by aditya-malte** [comment]
@CharlieBickerton , how about we combine out notebooks(yours with GPU and mine with TPU) and release a final version.
Do revert back if interested

**Comment by kimiyoung** [comment]
@CharlieBickerton @aditya-malte I think it's definitely a good idea if you could combine your notebooks! Let us know when it's ready :)

**Comment by CharlieBickerton** [comment]
@aditya-malte @kimiyoung Yes I agree combining is a good idea

**Comment by CharlieBickerton** [comment]
Hi All (@aditya-malte @kimiyoung ), I've been through the TPU notebook and I think it makes more sense to keep them separate. The GPU version is ready to run out of the box (it collects the imdb data, pretrained model and xlnet repo - and then trains a model). It saves the model within colab. 

I think the TPU version is a good starting point for more advanced usage, where as the GPU could slot into the README under the run_classifier.py imdb example. What are your thoughts?

Here is my cleaned version with output cleared: https://github.com/CharlieBickerton/xlnet/blob/master/XLNet_imdb_GPU.ipynb

**Comment by aditya-malte** [comment]
Hello @CharlieBickerton  @kimiyoung ,
I think it can be quite easily be integrated into one notebook by checking the use_tpu parameter or by checking the environment, I'll start working on the same to allow for a single self adapting notebook based on environment.
A unified notebook for GPU TPU would make it much easier for developers to use.
Thank you.

**Comment by CharlieBickerton** [comment]
Fair enough @aditya-malte , my reasoning behind thinking its not worth integrating was both the data collection step step and passing the parameters (i.e. regression classification or not) to run_classfier.py. Obviously one could integrate the two but I thought having a concrete example that works out of the box (on GPU) was worth having (@kimiyoung ). Then, consulting the docs and code is enough to edit the notebook to change task if you know what you are doing.

**Comment by kimiyoung** [comment]
Ok. Let's keep them separate for now.
