### ISSUE TITLE
Comparisons with Bert using same dataset

### ISSUE THREAD

**Issue by FisheWYZ** [zihangdai/xlnet#5]
I notice that XLNet uses Giga5 (16GB text) ClueWeb 2012-B (19GB), and Common Crawl (78GB) for pretraining. For a possibly better comparisons with Bert, I'm curious about what would be the performance if XLNet just uses BooksCorpus and English Wikipedia?

**Comment by wolfshow** [comment]
Yes, pretraining with different datasets may be not fair to compare with BERT

**Comment by AranKomat** [comment]
Ablation study was performed on the same training dataset (table 6), which shows what you want. But the result seems to me as if the substantial improvement is coming mostly from the use of Transformer-XL (i.e. larger context size). Probably using more data and greater context size is far more important than doing anything else.

**Comment by FisheWYZ** [comment]
> Ablation study was performed on the same training dataset (table 6), which shows what you want. But the result seems to me as if the substantial improvement is coming mostly from the use of Transformer-XL (i.e. larger context size). Probably using more data and greater context size is far more important than doing anything else.

Thank you man, I did miss this table. I haven't finished the experiment part. I also notice that the  Transformer-XL comes from the same authors. Nice work.

**Comment by junfenglx** [comment]
> Ablation study was performed on the same training dataset (table 6), which shows what you want. But the result seems to me as if the substantial improvement is coming mostly from the use of Transformer-XL (i.e. larger context size). Probably using more data and greater context size is far more important than doing anything else.

However, The authors just compare base model on the same dataset(pretraining and finetune).
They don't show the large models comparison info one the same pretraining dataset.
And the large xlnet model make a big improvement on these metrics.
