### ISSUE TITLE
Preprocess data for SQuAD 1.1

### ISSUE THREAD

**Issue by volker42maru** [zihangdai/xlnet#58]
First: Thanks for the great work and publishing all resources!

Question: Is there a way to preprocess the SQuAD 1.1. training data using `run_squad.py`?

I am using the `prepro_squad.sh` script with the v1.1 squad file as input and get the following error, because `is_impossible` keys are non-existent in this dataset:
```
Traceback (most recent call last):
  File "run_squad.py", line 1310, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_squad.py", line 1158, in main
    preprocess()
  File "run_squad.py", line 1129, in preprocess
    train_examples = read_squad_examples(FLAGS.train_file, is_training=True)
  File "run_squad.py", line 251, in read_squad_examples
    is_impossible = qa["is_impossible"]
KeyError: 'is_impossible'
```

I couldn't find a flag I could set to turn this off in the `run_squad` code.

**Comment by kimiyoung** [comment]
Right now training on SQuAD1.1 is not supported. There are two solutions: (1) it should not be difficult to modify `run_squad.py` to adapt to SQuAD1.1, (2) you might train on SQuAD2.0 and eval on SQuAD1.1 (which is what we did in our paper) without modifying the code.

**Comment by volker42maru** [comment]
I tried to train SQuAD2.0 and eval on SQuAD1.1. However, I don't get any useful results, i.e. predicted spans make no sense and F1 score is close to zero.

Eval on SQuAD2.0 works fine though.

**Comment by kimiyoung** [comment]
This looks weird to me. Could you try running eval with `--overwrite_data` to re-process the dev data for v1.1? Or run the official eval scripts against the output prediction file, `predict_dir/predictions.json`?

**Comment by volker42maru** [comment]
Thansk a lot, `--overwrite_data` did the trick. Probably, it was using data from previous SQuAD2.0 evals. 

One more question: I am trying to pre-train on additional data loading the large pre-trained model. However, I get an error when executing `train.py`:
```
  File "/content/xlnet/data_utils.py", line 868, in input_fn
    num_predict=num_predict)
  File "/content/xlnet/data_utils.py", line 757, in get_dataset
    bsz_per_core=bsz_per_core)
  File "/content/xlnet/data_utils.py", line 566, in parse_files_to_dataset
    dataset = tf.data.TFRecordDataset(dataset)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/readers.py", line 247, in __init__
    filenames, compression_type, buffer_size, num_parallel_reads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/readers.py", line 193, in __init__
    "`filenames` must be a `tf.data.Dataset` of `tf.string` elements.")
TypeError: `filenames` must be a `tf.data.Dataset` of `tf.string` elements
```

I preprocessed my corpus using `data_util.py` and then feed the tfrecords files to `train.py`

**Comment by kimiyoung** [comment]
It seems that the code found no input tfrecords. Please make sure that `record_info_dir` has corresponding tfrecord files.

**Comment by volker42maru** [comment]
Thanks, got it. There was an inconsistency in the .json file name, because `data_util.py` sets the uncased flag to `True` by default, while `train.py` sets it to `False` by default. 

Maybe it would be better to use the same default values here?

**Comment by LittlePea13** [comment]
If you want to train on SQUAD v1.1 data you can edit run_squad.py file. I did the following around line 250. This will allow to train both in v2.0 and v1.1:
```       
          if "is_impossible" in qa:
            is_impossible = qa["is_impossible"]
          else:
            is_impossible = False

**Comment by volker42maru** [comment]
Thanks for the hint :) I'll close this then
