### ISSUE TITLE
what is the memory length for the pretrain?

### ISSUE THREAD

**Issue by ewrfcas** [zihangdai/xlnet#59]
There is no mem_len in the code for pretrain.
python train.py
  --record_info_dir=$DATA/tfrecords \
  --train_batch_size=2048 \
  --seq_len=512 \
  --reuse_len=256 \
  --perm_size=256 \
  --n_layer=24 \
  --d_model=1024 \
  --d_embed=1024 \
  --n_head=16 \
  --d_head=64 \
  --d_inner=4096 \
  --untie_r=True \
  --mask_alpha=6 \
  --mask_beta=1 \
  --num_predict=85
The default mem_len in code is 70, but the memory length is 384 in the paper.
![image](https://user-images.githubusercontent.com/12042259/60149627-e8d55980-9807-11e9-999c-20559e37bd04.png)

**Comment by kimiyoung** [comment]
It's 384.

**Comment by ewrfcas** [comment]
Thanks a lot for you response @kimiyoung , but i have another question. If mem_len = 384 > reuse_len (256, seq_len//2), what is the effect of reuse_len (which I think is just a stride size,). I can't find any trace in the paper and the transformer-xl code.
Maybe reuse_len is used to make a_data in each sample always larger than 256 and the memory can be always controlled in the same context (with "curr_out = curr_out[:reuse_len]" )?

**Comment by ZizhenWang** [comment]
> Thanks a lot for you response @kimiyoung , but i have another question. If mem_len = 384 > reuse_len (256, seq_len//2), what is the effect of reuse_len (which I think is just a stride size). I can't find any trace in the paper and the transformer-xl code.
> Maybe reuse_len is used to make a_data in each sample always larger than 256 and the memory can be always controlled in the same context (with "curr_out = curr_out[:reuse_len]" )?

+1. same question.

**Comment by ZizhenWang** [comment]
And does the half-seq-len `reuse_len` means the segment length? because not all input sequence come from continue text?

**Comment by kimiyoung** [comment]
The input is represented as a huge sequence where document boundaries are denoted by the token `<eod>`. `reuse_len` here is to handle multiple segments, making sure that we only add segment A into memory.

**Comment by ewrfcas** [comment]
@kimiyoung Thanks!
