### ISSUE TITLE
what should I do？

### ISSUE THREAD

**Issue by Lenki777** [zihangdai/xlnet#6]
AttributeError: 'MirroredStrategy' object has no attribute 'num_replicas_in_sync' 
thx！

**Comment by Sara-HY** [comment]
> AttributeError: 'MirroredStrategy' object has no attribute 'num_replicas_in_sync'
> thx！

Hi, did you solve the problem and How? 
thx!

**Comment by Lenki777** [comment]
我更新了tensorflow 版本，之前因为cuda的原因用的cuda 9.0，tensorflow-gpu  是1.10，把tensorflow-gpu更新到1.13就可以跑啦

**Comment by Lenki777** [comment]
> > AttributeError: 'MirroredStrategy' object has no attribute 'num_replicas_in_sync'
> > thx！
> 
> Hi, did you solve the problem and How?
> thx!

我更新了tensorflow 版本，之前因为cuda的原因用的cuda 9.0，tensorflow-gpu 是1.10，把tensorflow-gpu更新到1.13就可以跑啦

**Comment by Kayal-Sampath** [comment]
> > > AttributeError: 'MirroredStrategy' object has no attribute 'num_replicas_in_sync'
> > > thx！
> > 
> > 
> > Hi, did you solve the problem and How?
> > thx!
> 
> 我更新了tensorflow 版本，之前因为cuda的原因用的cuda 9.0，tensorflow-gpu 是1.10，把tensorflow-gpu更新到1.13就可以跑啦

Was that solved?
