### ISSUE TITLE
Does the memory is considered as the same as seg A in segment level?

### ISSUE THREAD

**Issue by ZizhenWang** [zihangdai/xlnet#62]
I notice you set the memory SEG ID to `0` which is the same as seg A, as the following code
https://github.com/zihangdai/xlnet/blob/a68841431f4c616d27de3794f2581e4c2a17c4d7/modeling.py#L551-L560
so the memory token will be considered from the same segment as A. Is my understanding correct?
 
Thanks.

**Comment by kimiyoung** [comment]
That's right. This is intended for pretraining only right now.
