### ISSUE TITLE
train.py no module proto

### ISSUE THREAD

**Issue by 3NFBAGDU** [zihangdai/xlnet#63]
Traceback (most recent call last): File "train.py", line 16, in import tpu_estimator File "/home/ubuntu/xlnet/tpu_estimator.py", line 34, in from tensorflow.contrib.tpu.proto import compilation_result_pb2 as tpu_compilation_result ImportError: No module named proto.

what can i do to solve this problem.

**Comment by lukemelas** [comment]
Can you give more information on your computing setup? 

What TF version, are you using TPU, what TF version on TPU, where is your data, how did you preprocess it, what steps did you take to lead to this problem, etc.?

**Comment by 3NFBAGDU** [comment]
Hello,
When i run this command
./bazel-bin/src/spm_train --input=/home/ubuntu/xlnet/giorgi.txt --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995 --shuffle_input_sentence --input_sentence_size=100

i have the following error : """"./bazel-bin/src/spm_train --input=/home/ubuntu/xlnet/giorgi.txt --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995 --shuffle_input_sentence --input_sentence_size=10 WARNING: Logging before InitGoogleLogging() is written to STDERR I0628 08:51:36.717789 5255 sentencepiece_trainer.cc:52] Starts training with : TrainerSpec { input_format: model_prefix: sp10m.cased.v3 kModelType_Map: UNIGRAM vocab_size: 32000 self_test_sample_size: 0 character_coverage: 0.99995 input_sentence_size: 10 shuffle_input_sentence: 1 seed_sentencepiece_size: 1000000 shrinking_factor: 0.75 max_sentence_length: 4192 num_threads: 16 num_sub_iterations: 2 max_sentencepiece_length: 16 split_by_unicode_script: 1 split_by_number: 1 split_by_whitespace: 1 treat_whitespace_as_suffix: 0 vocabulary_output_piece_score: 1 hard_vocab_limit: 1 use_all_vocab: 0 unk_id: 0 bos_id: 1 eos_id: 2 pad_id: -1 unk_piece: bos_piece: eos_piece: pad_piece: unk_surface: ⁇ } NormalizerSpec { name: nmt_nfkc add_dummy_prefix: 1 remove_extra_whitespaces: 1 escape_whitespaces: 1 normalization_rule_tsv: } F0628 08:51:36.717953 5255 spm_train_main.cc:183] Check failed: _status.ok() Internal: src/trainer_interface.cc(54) [(trainer_spec.input().size()) > (0)] *** Check failure stack trace: *** Aborted (core dumped)""".


What type of extension should the --input file have?

**Comment by stefan-it** [comment]
@3NFBAGDU Yes, sentencepiece has some trouble at the moment 😒

I'm currently using the Python API Wrapper, so this should work:

```python
import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=bpe.input --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995 --model_type=unigram --control_symbols=<cls>,<sep>,<pad>,<mask>,<eod> --user_defined_symbols=<eop>,.,(,),",-,–,£,€ --shuffle_input_sentence --input_sentence_size=10000000')
```

**Comment by 3NFBAGDU** [comment]
Thank You,  I want to pretrain XLNET model on my custom data.  Is it possible to give -- input  my_data.txt file to train SentencePiece in my own data?

**Comment by stefan-it** [comment]
Yes, with `--input=` you should specify the training file :)

**Comment by 3NFBAGDU** [comment]
I have tried spm.SentencePieceTrainer.Train, but i have the error:
`Traceback (most recent call last):  File "giorgi.py", line 2, in <module>                                                                                     spm.SentencePieceTrainer.Train('--input=giorgi.txt --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995 --model_type=unigram --control_symbols=<cls>,<sep>,<pad>,<mask>,<eod> --user_defined_symbols=<eop>,.,(,),",-,–,£,€ --shuffle_input_sentence --input_sentence_size=10000000')                                                       RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(498) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())]`.

trainer_interface.cc(507) LOG(INFO) Saving model: sp10m.cased.v3.model.
Where can i find sp10m.cased.v3.model?

**Comment by 3NFBAGDU** [comment]
`RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(540) [output->WriteLine(os.str())]`, I have used sentencepiece, but i have this error while training.
