### ISSUE TITLE
Why the length of pos_emb with bidirectional data is 2*seq_len+mem_len

### ISSUE THREAD

**Issue by ewrfcas** [zihangdai/xlnet#65]
https://github.com/zihangdai/xlnet/blob/b4e33739b7df17af6f37a89af9a769a987711587/modeling.py#L205-L250

**Comment by xuerq** [comment]
The length of pos_emb is still  'seq_len+mem_len' in  XLNet .  
https://github.com/zihangdai/xlnet/blob/b4e33739b7df17af6f37a89af9a769a987711587/modeling.py#L170

The relative positional encodings in transformer-XL is unidirectional， but in XLNet is bidirectional.

**Comment by ewrfcas** [comment]
@xuerq Could it be undertood that bidirectional pos_emb in XLNet must be '2*seq_len+mem_len' at first, and then be reshaped+sliced to 'seq_len+mem_len' during the left-shift?

**Comment by xuerq** [comment]
@ewrfcas Yeah, I think so

**Comment by ewrfcas** [comment]
We need more code comments here.

**Comment by kimiyoung** [comment]
> @xuerq Could it be undertood that bidirectional pos_emb in XLNet must be '2*seq_len+mem_len' at first, and then be reshaped+sliced to 'seq_len+mem_len' during the left-shift?

That's right. Will add more comments later.

**Comment by ewrfcas** [comment]
@kimiyoung Thanks!
