### ISSUE TITLE
xlnet for Quora Questions Dataset

### ISSUE THREAD

**Issue by aisheh90** [zihangdai/xlnet#71]
Hello,

I saw in Papers with code website, xlnet accuracy on Quora question pairs is 90.3%.
Any has the code of apply xlnet on Quora dataset?
[https://paperswithcode.com/paper/xlnet-generalized-autoregressive-pretraining](url)
Thanks,

**Comment by kimiyoung** [comment]
This is similar to MNLI. You can just write a QQP processor similar to the MNLI processor with custom data loading. See `run_classifier.py`.
