### ISSUE TITLE
Does get_pooled_out return the output of the final CLS token or of the final PAD token?

### ISSUE THREAD

**Issue by Enumaris** [zihangdai/xlnet#73]
I'm trying to use the model given in xlnet.py. I want to input my sequences like [A,SEP,B,SEP,CLS,PAD,PAD,...] padded up to a set sequence length. When I call `get_pooled_out()` on such an input using `summary_type='last'`, am I getting the embedding for that CLS token in the middle there or for the last PAD token? 

I ask because when I look at the call to `summarize_sequence` in xlnet.py, I see:
```
summary = modeling.summarize_sequence(
          summary_type=summary_type,
          hidden=self.output,
...
```
And modeling.summarize_sequence() says:
```
if summary_type == 'last':
      summary = hidden[-1]
```

Which suggests I'm just going to get the embedding for the actual last token, which would be (often) a PAD token... What I want though is the embedding for the CLS token. Is `self.output`  truncated for all the PAD tokens? But wouldn't that make your batches non-uniform in length?

**Comment by kimiyoung** [comment]
You will get the embedding for PAD in this case. In `run_classifier.py`, we pad the sequence at the beginning, which becomes [PAD, PAD, ..., A, SEP, B, SEP, CLS].

**Comment by Enumaris** [comment]
Ah, I see! That makes sense, I will pad from the beginning as well then.
