### ISSUE TITLE
How to save/print the predictions in run_race.py

### ISSUE THREAD

**Issue by Sumeghtech** [zihangdai/xlnet#89]
How should we save the `predictions` tensor as output from `tf.argmax` in `Line 388` of  `run_race.py` or print the value?

Would be good if you can point out or write some small code snippet to show that.

Thanks @kimiyoung and @zihangdai

**Comment by kimiyoung** [comment]
https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator?hl=fa#predict

**Comment by Sumeghtech** [comment]
Thanks for replying @kimiyoung .

But doing `for results in estimator.predict(input_fn=eval_input_fn): print(results)` I'm getting 
`ValueError: Missing predictions.`

**Comment by Sumeghtech** [comment]
Hi!

Can you see issue #89 in the XLnet repo in GitHub.

Actually, I tried doing

*for results in estimator.predict(input_fn=eval_input_fn):*
*print(results) *

I'm getting a *ValueError: Missing Predictions*

I added this code in *Line 539* of run_race.py
